#!/bin/sh
mount -t devtmpfs devtmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys
echo "Loading OpenDLA kernel module..."
insmod /opendla.ko
echo " "
echo "##################################"
echo "#    Cheshire Linux Booted!      #"
echo "##################################"
echo " "
echo "Starting shell..."
exec setsid cttyhack /bin/sh
